# -*- coding: utf-8 -*-
"""new_Notion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GMsLHK_hG2EPPdJ8yEa2yQVce_8MXRMd
"""

! pip install requests notion-client beautifulsoup4 python-dotenv

NOTION_TOKEN='XXX-000000000000o000000000000000000000000000000000' #private token
NOTION_DATABASE_ID='0000000000000' #URL



! pip install requests notion-client beautifulsoup4

import html
import re
from typing import Any

import requests
from bs4 import BeautifulSoup



NOTION_TOKEN=NOTION_TOKEN #'00000000000'private Token
NOTION_DATABASE_ID='3023b9794b2480d3bce6f3f645ccd7d8'

SCHAEFFLER_API_URL = (
    "https://searchui.search.windows.net/indexes/"
    "schaeffler-prod/docs/search?api-version=2020-06-30"
)

SCHAEFFLER_API_KEY = "key"

SCHAEFFLER_HEADERS = {
    "accept": "*/*",
    "content-type": "application/json;charset=UTF-8",
    "api-key": SCHAEFFLER_API_KEY,
    "origin": "https://jobs.schaeffler.com",
    "referer": "https://jobs.schaeffler.com/",
    "user-agent": "Mozilla/5.0",
}


SCHAEFFLER_PAYLOAD = {
    "count": False,
    "facets": [],
    "filter": (
        "(addresses/any(jt: jt/countryCity eq 'Deutschland:Bebra') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Berlin') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Bühl') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Chemnitz') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Dortmund') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Erlangen') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Frankfurt am Main') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Gunzenhausen') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Halle') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Hamburg') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Herzogenaurach') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Hirschaid') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Höchstadt') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Homburg') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Kappelrodeck') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Karlsruhe') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Kitzingen') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Lahr') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Limbach-Oberfrohna') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:München') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Nürnberg') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Regensburg') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Schwalbach') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Schweinfurt')) "
        "and (jobTypeId eq 'RC_jobTypeParent_StudentsTrainees:IN') "
        "and language eq 'de_DE'"
    ),
    "search": "*",
    "skip": 0,
    "top": 1000,
}

NOTION_HEADERS = {
    "Authorization": f"Bearer {NOTION_TOKEN}",
    "Notion-Version": "2022-06-28",
    "Content-Type": "application/json",
}



def clean_text(value: str, limit: int = 1900) -> str:
    if not value:
        return ""
    value = re.sub(r"\s+", " ", value).strip()
    return value[:limit]


def html_to_text(raw_html: str, limit: int = 1900) -> str:
    if not raw_html:
        return ""
    unescaped = html.unescape(raw_html)
    soup = BeautifulSoup(unescaped, "html.parser")
    return clean_text(soup.get_text(" ", strip=True), limit=limit)


def unique_keep_order(items: list[str]) -> list[str]:
    seen = set()
    result = []
    for item in items:
        if item and item not in seen:
            seen.add(item)
            result.append(item)
    return result

##----

def fetch_jobs() -> list[dict[str, Any]]:
    resp = requests.post(
        SCHAEFFLER_API_URL,
        headers=SCHAEFFLER_HEADERS,
        json=SCHAEFFLER_PAYLOAD,
        timeout=30,
    )
    resp.raise_for_status()
    data = resp.json()
    return data.get("value", [])


def get_external_id(job: dict[str, Any]) -> str:
    return clean_text(str(job.get("applyUrl") or ""), limit=300)


def get_title(job: dict[str, Any]) -> str:
    candidates = [
        job.get("title"),
        job.get("jobTitle"),
        job.get("name"),
        job.get("headline"),
        html_to_text(job.get("descriptionHeader", ""), limit=300),
    ]
    for candidate in candidates:
        txt = clean_text(str(candidate or ""), limit=200)
        if txt:
            return txt
    return f"Schaeffler Job {get_external_id(job) or 'Unknown'}"


def get_category(job: dict[str, Any]) -> str:
    value = job.get("jobFamily", [])
    if isinstance(value, list):
        return clean_text(", ".join(str(x) for x in value if x))
    return clean_text(str(value or ""))


def get_employment_type(job: dict[str, Any]) -> str:
    for key in ["experienceLevel", "employmentType", "jobType", "workerSubType"]:
        value = clean_text(str(job.get(key) or ""), limit=100)
        if value:
            return value
    return ""


def get_location(job: dict[str, Any]) -> str:
    addresses = job.get("addresses", [])
    parts: list[str] = []

    if isinstance(addresses, list):
        for addr in addresses:
            if not isinstance(addr, dict):
                continue
            city = addr.get("city")
            country_city = addr.get("countryCity")
            location = city or country_city
            if location:
                parts.append(str(location))

    return clean_text(", ".join(unique_keep_order(parts)))


def get_description(job: dict[str, Any]) -> str:
    return html_to_text(job.get("description", ""), limit=1900)


def get_posted_at(job: dict[str, Any]) -> str:
    return str(job.get("datePosted") or "").strip()


def get_source_url(job: dict[str, Any]) -> str:
    apply_value = str(job.get("applyUrl") or "").strip()
    if not apply_value:
        return ""

    if apply_value.startswith("http://") or apply_value.startswith("https://"):
        return apply_value

    return f"https://jobs.schaeffler.com/job/-/{apply_value}/"


# =========================
## Notion HTTP API
# =========================

def notion_query_database_by_external_id(external_id: str) -> list[dict[str, Any]]:
    url = f"https://api.notion.com/v1/databases/{NOTION_DATABASE_ID}/query"
    payload = {
        "filter": {
            "property": "External ID",
            "rich_text": {
                "equals": external_id
            }
        }
    }

    resp = requests.post(url, headers=NOTION_HEADERS, json=payload, timeout=30)
    resp.raise_for_status()
    return resp.json().get("results", [])


def build_notion_properties(job):
    title = get_title(job)
    external_id = get_external_id(job)
    category = get_category(job)
    employment_type = get_employment_type(job)
    description = get_description(job)
    posted_at = get_posted_at(job)
    source_url = get_source_url(job)
    location = get_location(job)
    active = "true" if bool(job.get("isActive", True)) else "false"

    props = {
        "Job Title": {
            "title": [{"text": {"content": title[:200]}}]
        },
        "External ID": {
            "rich_text": [{"text": {"content": external_id[:300]}}]
        },
        "Category": {
            "rich_text": [{"text": {"content": category[:1900]}}]
        },
        "Description": {
            "rich_text": [{"text": {"content": description[:1900]}}]
        },
        "Source URL": {
            "rich_text": [{"text": {"content": source_url[:1900]}}]
        },

        "Active": {
            "rich_text": [{"text": {"content": active}}]
        },
        "Employment Type": {
            "rich_text": [{"text": {"content": employment_type[:200]}}]
        },
        "Posted At": {
            "rich_text": [{"text": {"content": posted_at[:200]}}]
        }
    }

    return props


def notion_create_page(properties: dict[str, Any]) -> dict[str, Any]:
    url = "https://api.notion.com/v1/pages"
    payload = {
        "parent": {"database_id": NOTION_DATABASE_ID},
        "properties": properties
    }
    resp = requests.post(url, headers=NOTION_HEADERS, json=payload, timeout=30)
    resp.raise_for_status()
    return resp.json()


def notion_update_page(page_id: str, properties: dict[str, Any]) -> dict[str, Any]:
    url = f"https://api.notion.com/v1/pages/{page_id}"
    payload = {
        "properties": properties
    }
    resp = requests.patch(url, headers=NOTION_HEADERS, json=payload, timeout=30)
    resp.raise_for_status()
    return resp.json()


def upsert_job(job: dict[str, Any]) -> None:
    external_id = get_external_id(job)
    if not external_id:
        print("Skipped job without external_id")
        return

    properties = build_notion_properties(job)
    existing = notion_query_database_by_external_id(external_id)

    if existing:
        page_id = existing[0]["id"]
        notion_update_page(page_id, properties)
        print(f"Updated: {get_title(job)}")
    else:
        notion_create_page(properties)
        print(f"Created: {get_title(job)}")


#

def main() -> None:
    jobs = fetch_jobs()
    print(f"Fetched {len(jobs)} jobs")

    for job in jobs:
        try:
            upsert_job(job)
        except requests.HTTPError as e:
            response_text = ""
            try:
                response_text = e.response.text[:1000]
            except Exception:
                pass
            print(f"HTTP error on job {job.get('applyUrl')}: {e}")
            if response_text:
                print(response_text)
        except Exception as e:
            print(f"Failed on job {job.get('applyUrl')}: {e}")


if __name__ == "__main__":
    main()









import html
import re
from typing import Any

import requests
from bs4 import BeautifulSoup


NOTION_TOKEN='token'
NOTION_DATABASE_ID='url'

SCHAEFFLER_API_URL = (
    "https://searchui.search.windows.net/indexes/"
    "schaeffler-prod/docs/search?api-version=2020-06-30"
)

SCHAEFFLER_API_KEY = "key"

SCHAEFFLER_HEADERS = {
    "accept": "*/*",
    "content-type": "application/json;charset=UTF-8",
    "api-key": SCHAEFFLER_API_KEY,
    "origin": "https://jobs.schaeffler.com",
    "referer": "https://jobs.schaeffler.com/",
    "user-agent": "Mozilla/5.0",
}


SCHAEFFLER_PAYLOAD = {
    "count": False,
    "facets": [],
    "filter": (
        "(addresses/any(jt: jt/countryCity eq 'Deutschland:Bebra') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Berlin') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Bühl') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Chemnitz') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Dortmund') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Erlangen') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Frankfurt am Main') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Gunzenhausen') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Halle') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Hamburg') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Herzogenaurach') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Hirschaid') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Höchstadt') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Homburg') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Kappelrodeck') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Karlsruhe') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Kitzingen') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Lahr') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Limbach-Oberfrohna') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:München') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Nürnberg') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Regensburg') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Schwalbach') "
        "or addresses/any(jt: jt/countryCity eq 'Deutschland:Schweinfurt')) "
        "and (jobTypeId eq 'RC_jobTypeParent_StudentsTrainees:IN') "
        "and language eq 'de_DE'"
    ),
    "search": "*",
    "skip": 0,
    "top": 1000,
}

NOTION_HEADERS = {
    "Authorization": f"Bearer {NOTION_TOKEN}",
    "Notion-Version": "2022-06-28",
    "Content-Type": "application/json",
}



TAG_KEYWORDS = {
    "Agentic": [
        "agentic", "agent", "ai agent", "autonomous agent"
    ],
    "KI/AI": [
        "ki", "künstliche intelligenz", "artificial intelligence",
        "ai", "machine learning", "ml", "deep learning",
        "nlp", "llm", "generative ai"
    ],
    "Business": [
        "business", "strategy", "strategic", "marketing",
        "sales", "product management", "consulting",
        "geschäft", "unternehmens", "controlling"
    ],
    "Data/Analyse": [
        "data", "data science", "data scientist", "data analyst",
        "analytics", "analysis", "analyse", "reporting",
        "dashboard", "sql", "bi", "business intelligence"
    ],
}


ONLY_SAVE_MATCHED_JOBS = True


def clean_text(value: str, limit: int = 1900) -> str:
    if not value:
        return ""
    value = re.sub(r"\s+", " ", value).strip()
    return value[:limit]


def html_to_text(raw_html: str, limit: int = 1900) -> str:
    if not raw_html:
        return ""
    unescaped = html.unescape(raw_html)
    soup = BeautifulSoup(unescaped, "html.parser")
    return clean_text(soup.get_text(" ", strip=True), limit=limit)


def join_text_parts(parts: list[str]) -> str:
    return clean_text(" ".join(p for p in parts if p), limit=20000)



def fetch_jobs() -> list[dict[str, Any]]:
    resp = requests.post(
        SCHAEFFLER_API_URL,
        headers=SCHAEFFLER_HEADERS,
        json=SCHAEFFLER_PAYLOAD,
        timeout=30,
    )
    resp.raise_for_status()
    data = resp.json()
    return data.get("value", [])


def get_external_id(job: dict[str, Any]) -> str:
    return clean_text(str(job.get("applyUrl") or ""), limit=300)


def get_title(job: dict[str, Any]) -> str:
    candidates = [
        job.get("title"),
        job.get("jobTitle"),
        job.get("name"),
        job.get("headline"),
        html_to_text(job.get("descriptionHeader", ""), limit=300),
    ]
    for candidate in candidates:
        txt = clean_text(str(candidate or ""), limit=200)
        if txt:
            return txt
    return f"Schaeffler Job {get_external_id(job) or 'Unknown'}"


def get_category(job: dict[str, Any]) -> str:
    value = job.get("jobFamily", [])
    if isinstance(value, list):
        return clean_text(", ".join(str(x) for x in value if x))
    return clean_text(str(value or ""))


def get_employment_type(job: dict[str, Any]) -> str:
    for key in ["experienceLevel", "employmentType", "jobType", "workerSubType"]:
        value = clean_text(str(job.get(key) or ""), limit=100)
        if value:
            return value
    return ""


def get_description(job: dict[str, Any]) -> str:
    return html_to_text(job.get("description", ""), limit=1900)


def get_posted_at(job: dict[str, Any]) -> str:
    return str(job.get("datePosted") or "").strip()


def get_source_url(job: dict[str, Any]) -> str:
    apply_value = str(job.get("applyUrl") or "").strip()
    if not apply_value:
        return ""

    if apply_value.startswith("http://") or apply_value.startswith("https://"):
        return apply_value

    return f"https://jobs.schaeffler.com/job/-/{apply_value}/"


def get_search_text(job: dict[str, Any]) -> str:
    parts = [
        get_title(job),
        get_category(job),
        get_employment_type(job),
        get_description(job),
    ]
    return join_text_parts(parts).lower()


def get_tags(job: dict[str, Any]) -> list[str]:
    text = get_search_text(job)
    tags = []

    for tag, keywords in TAG_KEYWORDS.items():
        if any(keyword.lower() in text for keyword in keywords):
            tags.append(tag)

    return tags


def is_relevant_job(job: dict[str, Any]) -> bool:
    tags = get_tags(job)
    return len(tags) > 0


# =========================
#  Notion HTTP API
# =========================

def notion_query_database_by_external_id(external_id: str) -> list[dict[str, Any]]:
    url = f"https://api.notion.com/v1/databases/{NOTION_DATABASE_ID}/query"
    payload = {
        "filter": {
            "property": "External ID",
            "rich_text": {
                "equals": external_id
            }
        }
    }

    resp = requests.post(url, headers=NOTION_HEADERS, json=payload, timeout=30)
    resp.raise_for_status()
    return resp.json().get("results", [])


def build_notion_properties(job: dict[str, Any]) -> dict[str, Any]:
    title = get_title(job)
    external_id = get_external_id(job)
    category = get_category(job)
    employment_type = get_employment_type(job)
    description = get_description(job)
    posted_at = get_posted_at(job)
    source_url = get_source_url(job)
    active = "true" if bool(job.get("isActive", True)) else "false"
    tags = ", ".join(get_tags(job))

    props = {
        "Job Title": {
            "title": [
                {"text": {"content": title[:200]}}
            ]
        },
        "External ID": {
            "rich_text": [
                {"text": {"content": external_id[:300]}}
            ]
        },
        "Category": {
            "rich_text": [
                {"text": {"content": category[:1900]}}
            ]
        },
        "Description": {
            "rich_text": [
                {"text": {"content": description[:1900]}}
            ]
        },
        "Source URL": {
            "rich_text": [
                {"text": {"content": source_url[:1900]}}
            ]
        },
        "Active": {
            "rich_text": [
                {"text": {"content": active}}
            ]
        },
        "Employment Type": {
            "rich_text": [
                {"text": {"content": employment_type[:200]}}
            ]
        },
        "Posted At": {
            "rich_text": [
                {"text": {"content": posted_at[:200]}}
            ]
        }
    }

    return props


def notion_create_page(properties: dict[str, Any]) -> dict[str, Any]:
    url = "https://api.notion.com/v1/pages"
    payload = {
        "parent": {"database_id": NOTION_DATABASE_ID},
        "properties": properties
    }
    resp = requests.post(url, headers=NOTION_HEADERS, json=payload, timeout=30)
    resp.raise_for_status()
    return resp.json()


def notion_update_page(page_id: str, properties: dict[str, Any]) -> dict[str, Any]:
    url = f"https://api.notion.com/v1/pages/{page_id}"
    payload = {"properties": properties}
    resp = requests.patch(url, headers=NOTION_HEADERS, json=payload, timeout=30)
    resp.raise_for_status()
    return resp.json()


def upsert_job(job: dict[str, Any]) -> None:
    external_id = get_external_id(job)
    if not external_id:
        print("Skipped job without external_id")
        return

    properties = build_notion_properties(job)
    existing = notion_query_database_by_external_id(external_id)

    if existing:
        page_id = existing[0]["id"]
        notion_update_page(page_id, properties)
        print(f"Updated: {get_title(job)} | Tags: {', '.join(get_tags(job))}")
    else:
        notion_create_page(properties)
        print(f"Created: {get_title(job)} | Tags: {', '.join(get_tags(job))}")


# =========================
# 6) 主程序
# =========================

def main() -> None:
    jobs = fetch_jobs()
    print(f"Fetched {len(jobs)} student jobs")

    relevant_jobs = []
    for job in jobs:
        if not ONLY_SAVE_MATCHED_JOBS or is_relevant_job(job):
            relevant_jobs.append(job)

    print(f"Matched {len(relevant_jobs)} jobs for Agentic/KI/Business/Data/Analyse")

    for job in relevant_jobs:
        try:
            upsert_job(job)
        except requests.HTTPError as e:
            response_text = ""
            try:
                response_text = e.response.text[:1000]
            except Exception:
                pass
            print(f"HTTP error on job {job.get('applyUrl')}: {e}")
            if response_text:
                print(response_text)
        except Exception as e:
            print(f"Failed on job {job.get('applyUrl')}: {e}")


if __name__ == "__main__":
    main()